config/routes.rb
EmmPhase2::Application.routes.draw do
 
  resources :admins
  resources :customers
  resources :loginlogs
  resources :electricities
  resource :dashboards
  resource :settings
  resource :countries
  resource :states
  resource :cities
  resource :positions
  match "/state_change" => "admins#state_change"
  match "/city_change" => "admins#city_change"
  match "/" => "admins#sign_in"
  match "/customer/action" => "customers#action"
  match "sign_in" => "admins#sign_in"
  match "sign_in_act" => "admins#sign_in_act"
  match "/admin" => "admins#index"
  match "/signout" => "admins#sign_out"
  match "/signin" => "admins#sign_in"
  match "/loginlog/action" => "loginlogs#action"
  match "/admin/action" => "admins#action"
  match "/dashboard" => "dashboards#index"
  match "/setting" => "settings#index"
  match "/customer" => "customers#index"
  match "/loginlog" => "loginlogs#index"
  match "/electricity" => "electricities#index"
  match "/meterreading" => "electricities#import_csv"
  match "/test" => "electricities#test"
  match "/insert_to_customer_panel" => "electricities#insert_to_customer_panel"
  match "/cron_test" => "electricities#cron_test"
  
  
  match "/country" => "countries#index"
  match "/country/action" => "countries#action"
  match "/state" => "states#index"
  match "/state/action" => "states#action"
  match "/city" => "cities#index"
  match "/city/action" => "cities#action"
  match "/position" => "positions#index"
  match "/position/action" => "positions#action"
  
 
  
  

   root :to => 'admins#sign_in'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :first_name, :last_name, :email, :password, :status,:current_ip,:email2, :country_id, :state_id, :city_id, :zip_code, :phone, :phone1, :mobile
  validates_presence_of :first_name,:last_name,:email,:email2, :country_id, :state_id, :city_id, :zip_code, :phone, :phone1, :mobile
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => " Invalid Format"
  validates_format_of :email2, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => " Invalid Format"
  validates :email,:uniqueness => true,:on => :create
  validates_presence_of :password,:on => :create
  validates_length_of :password, :minimum => 6, :too_short => "needs minimun 6 character",:on => :create
  
   def self.cron_job
     # logger.info Time.now.to_s
      # puts "Just do it"
       logger.debug "Just do it"
   end
  
  def self.addadmin
    @admin = Admin.new
    @admin.first_name = 'test'
    @admin.last_name = 'test'
    @admin.email = 'aa@gmail.com'
    @admin.password = 'aaaaaa'
    @admin.status = 'active'
    @admin.current_ip='192.168.1.4'
    @admin.save
  end
  task :addadmin => :environment do
    @admin = Admin.new
    @admin.first_name = 'test'
    @admin.last_name = 'test'
    @admin.email = 'aa@gmail.com'
    @admin.password = 'aaaaaa'
    @admin.status = 'active'
    @admin.current_ip='192.168.1.4'
    @admin.save
  end
  
  
end

app/models/city.rb
class City < ActiveRecord::Base
   attr_accessible :state_id, :name, :code, :description, :status
   validates_presence_of :state_id, :name, :code, :description, :status
    belongs_to :state
end

app/models/country.rb
class Country < ActiveRecord::Base
   attr_accessible :name, :code, :description, :status
   validates_presence_of :name, :code, :description, :status
   has_many :states,:dependent => :destroy
end

app/models/csvinfo.rb
class Csvinfo < ActiveRecord::Base
  attr_accessible :customer_id, :name,:verified,:loaded,:totaldata,:view,:status,:upload_date
  has_many :customers,:dependent => :destroy
  belongs_to :meter_reading
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :customer_id,:name,:email,:licence_id,:status,:city,:country,:postalcode,:phone,:phone_code,:heroku_url,:heroku_username,:heroku_password,:git_url,:amazon_url,:db_host,:db_name,:db_username,:db_password,:db_port
  belongs_to :csvinfo
  validates_presence_of :customer_id,:name,:email,:licence_id,:status,:city,:country,:postalcode,:phone,:phone_code,:heroku_url,:heroku_username,:git_url,:amazon_url,:db_host,:db_name,:db_username,:db_password,:db_port
  validates_presence_of :heroku_password,:on => :create
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => " Invalid Format"
  validates :email,:uniqueness => true,:on => :create
end

app/models/electricity_reading.rb
#require 'time_utils'

class ElectricityReading < ActiveRecord::Base
  attr_accessible :meter_id,:start_time,:end_time,:mid_time,:electricity_upload_id,:user_id,:electricity_value
  
end

app/models/gas_reading.rb
#require 'time_utils'

class GasReading < ActiveRecord::Base
  attr_accessible :meter_id,:start_time,:end_time,:mid_time,:gas_upload_id,:user_id,:gas_value
  
end

app/models/loginlog.rb
class Loginlog < ActiveRecord::Base
   attr_accessible :first_name,:last_name, :email,:login_time,:logout_time,:ip
end

app/models/meter.rb
class Meter < ActiveRecord::Base
end

app/models/meter_reading.rb
class MeterReading < ActiveRecord::Base
  attr_accessible :csvinfo_id, :meter_ip,:meter_id,:usuage_value,:start_time,:end_time,:kwh,:customer_id
  has_many :csvinfos,:dependent => :destroy
end

app/models/position.rb
class Position < ActiveRecord::Base
   attr_accessible :title, :status
   validates_presence_of :title, :status
end

app/models/state.rb
class State < ActiveRecord::Base
   attr_accessible :country_id, :name, :code, :description, :status
   validates_presence_of :country_id, :name, :code, :description, :status
   belongs_to :country
   has_many :cities
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/electricities_helper.rb
module ElectricitiesHelper
end

app/helpers/loginlogs_helper.rb
module LoginlogsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/admins/_city.html.erb
<%= select("admin", "city_id", @cities.collect {|p| [ p.name, p.id ] }, { :prompt => "Select City"},:class=>"span8") %>

app/views/admins/_form.html.erb
<div class="container-fluid">
    <div class="row-fluid">
    <div class="span10">
         <!--div class="page-header">
        <h2>Add Customer</h2>
        </div-->
        <ul class="breadcrumb">
        <li><a href="#">Home</a> <span class="divider">/</span></li>
          <%if @admin.id.nil?%>
            <li class="active">Add Administrator</li>
          <%else%>
            <li class="active">Edit Administrator</li>
          <%end%>
        </ul>
        <!--div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">?</button>
        <strong>Oh snap!</strong> Change a few things up and try submitting again.
        </div-->
        
        <%= form_for(@admin,:html=>{:class=>"form-horizontal"}) do |f| %>
        <% if @admin.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <strong><%=@admin.errors.full_messages[0] %></strong>
          </div>
        <% end %>
        <div class="span5 well">
          <!--form class="form-horizontal"-->
        <h4>Primary Information</h4>
          <div class="control-group">
            <%= f.label :first_name ,:class=>"control-label"%>
              <div class="controls">
                <%= f.text_field :first_name,:class=>"span8",:placeholder=>"First Name"%>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :last_name,:class=>"control-label"%>
              <div class="controls">
                <%= f.text_field :last_name,:class=>"span8",:placeholder=>"Last Name"%>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :email,:class=>"control-label"%>
              <div class="controls">
                <%= f.text_field :email,:class=>"span8",:placeholder=>"Email"%>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :password,:class=>"control-label"%>
              <div class="controls">
                <%= f.password_field:password,:class=>"span8",:placeholder=>"Password"%>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :status,:class=>"control-label"%>
              <div class="controls">
                <%= f.select :status, [['Active','active'],['Inactive','inactive']],{},{:class => 'span8'} %>
                <br><br>
                   <%= f.submit 'Submit',:class=>'btn'%>
              </div>
          </div>
        <!--/form-->
        </div>
        <div class="span5 well">
            <form class="form-horizontal">
        <h4>Contact Information</h4>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Alternet Email address</label>
            <div class="controls">
              <%= f.text_field :email2,:class=>"span8",:placeholder=>"Alternet Email address "%>
            </div>
            </div>
          <div class="control-group">
            <%= f.label :country_id,:class=>"control-label"%>
              <div class="controls" id="c_country">
                <%= select("admin", "country_id", Country.all.collect {|p| [ p.name, p.id ] }, { :prompt => "Select Country"},:class=>"span8") %>
               <%#= select_tag("admin[country_id]", options_from_collection_for_select(Country.all, "id", "name", params[:country_id].to_i),:class=>"span8") %>
              </div>
          </div>        

          <div class="control-group">
            <%= f.label :state_id,:class=>"control-label"%>
              <div class="controls" id="c_state">
                <%= select("admin", "state_id", State.all.collect {|p| [ p.name, p.id ] }, { :prompt => "Select State"},:class=>"span8") %>
               <%#= select_tag("admin[state_id]", options_from_collection_for_select(State.all, "id", "name", params[:state_id].to_i),:class=>"span8") %>
              </div>
          </div>        

          <div class="control-group">
            <%= f.label :city_id,:class=>"control-label"%>
              <div class="controls" id="c_city">
                <%= select("admin", "city_id", City.all.collect {|p| [ p.name, p.id ] }, { :prompt => "Select City"},:class=>"span8") %>
               <%#= select_tag("admin[city_id]", options_from_collection_for_select(City.all, "id", "name", params[:city_id].to_i),:class=>"span8") %>
              </div>
          </div>  
        <div class="control-group">
            <label class="control-label" for="inputEmail">Zip Code</label>
            <div class="controls">
              <%= f.text_field :zip_code,:class=>"span8",:placeholder=>"Zip Code"%>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Primary Phone</label>
            <div class="controls">
              <%= f.text_field :phone,:class=>"span8",:placeholder=>"Primary Phone"%>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Alternet Phone </label>
            <div class="controls">
              <%= f.text_field :phone1,:class=>"span8",:placeholder=>"Alternet Phone "%>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Cell Number</label>
            <div class="controls">
              <%= f.text_field :mobile,:class=>"span8",:placeholder=>"Cell Number"%>
            </div>
        </div>
        <!--/form-->
        </div>
        
        <!--/form-->
        </div>        
      <%end%>
    </div>
    </div>	
</div><!--/.fluid-container-->



<script>
  
$("#admin_country_id").change(function(){
	$.ajax({
	url: '/state_change',
	type: "POST",
	data: {'id':$(this).val()},
	//dataType: 'json',
	success: function (data) {
		//alert(data);return false;
		$("#c_state").html(data);
	}
	});
	 
});

$("#admin_state_id").change(function(){
	$.ajax({
	url: '/city_change',
	type: "POST",
	data: {'id':$(this).val()},
	//dataType: 'json',
	success: function (data) {
		//alert(data);return false;
		$("#c_city").html(data);
	}
	});
	 
});

  
</script>

<!--
<%#= form_for(@post) do |f| %>
  <%# if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <%# @post.errors.full_messages.each do |msg| %>
        <li><%#= msg %></li>
      <%# end %>
      </ul>
    </div>
  <%# end %>

  <div class="field">
    <%#= f.label :name %><br />
    <%#= f.text_field :name %>
  </div>
  <div class="field">
    <%#= f.label :title %><br />
    <%#= f.text_field :title %>
  </div>
  <div class="field">
    <%#= f.label :content %><br />
    <%#= f.text_area :content %>
  </div>
  <div class="actions">
    <%#= f.submit %>
  </div>
<%# end %>
-->

app/views/admins/_state.html.erb
<%= select("admin", "state_id", @states.collect {|p| [ p.name, p.id ] }, { :prompt => "Select State"},:class=>"span8") %>

app/views/admins/edit.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="page-header">
      <h2>Edit Administrator</h2>
    </div>

<%= render 'form' %>
  </div>
</div>
<%#= link_to 'Show', @post %> |
<%#= link_to 'Back', posts_path %>

app/views/admins/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
  <div class="span10">
      <div class="page-header">
      <h2>Administrators</h2>
      </div>
      <ul class="breadcrumb">
      <li><a href="#">Home</a> <span class="divider">/</span></li>
      <li class="active">Administrators</li>
      </ul>
      <% if flash[:msg]%>
        <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert">x</button>
              <strong>Well done!</strong><%=flash[:msg]%>
        </div>
      <%end%>
      <div class="left_topform">
      <form class="form-search" action="/admin" name="sfrm" id="sfrm" method="put">
      <%#form_for '',:controller => 'admins',:url => {:action => 'index'} do -%>
        <%=text_field_tag 'keyword',params[:keyword],:class => 'input-large search-query'%>
        <%=select_tag 'option', options_for_select([["Select Field",""],["First Name","first_name"],["Last Name","last_name"], ["Email","email"],["Status","status"]], params[:option])%>

      <button type="submit" class="btn btn-primary">Search</button>
    <%#end%>
      </form>
      </div>
      <form class="form-search" action="/admin/action" name="cfrm" id="cfrm" method="put">
        <input type="hidden" name="action_val" id ="action_val" value="">

      <div class="pull-right">
      <button type="submit" class="btn btn-inverse" onclick="return Action(document.cfrm,'active');">Make Active</button>
      <button type="submit" class="btn btn-inverse" onclick="return Action(document.cfrm,'inactive');">Make Inactive</button>
      <button type="submit" class="btn btn-inverse" onclick="return Action(document.cfrm,'delete');">Delete</button>
      <%= link_to 'New Administrator', new_admin_path ,:class=>"btn btn-inverse"%>
      </div>

      <div class="clearfix"></div>
      <!--div ><b> Total Number Of Records : </b><%=@admins.count%></div-->
      <%if @admins.length > 0%>
      <table class="table table-bordered table-striped ">
        <thead>
        <tr>
          <th><input type="checkbox" onclick="checkAll(document.cfrm);" name="check_all" id="check_all"></th>
          <th>Name</th>
          <!--th>Last Name</th-->
          <th>Email</th>
          <th>Last Login IP</th>
          <th>Status</th>
          <th>Created Date</th>
        </tr>
        </thead>

        <% @admins.each do |admin| %>
          <thead>
          <tr>
          <td><input type="checkbox" id="iId" value="<%=admin.id%>" name="chk[]" ></td>
          <td><%= link_to admin.first_name+' '+admin.last_name ,edit_admin_path(admin)%></td>
          <!--td><%= admin.last_name %></td-->
          <td><%= admin.email %></td>
          <td><%= admin.current_ip %></td>
          <td><%= admin.status.capitalize %></td>
          <td><%= admin.created_at.strftime("%d %B %Y  %M:%H") %></td>
        </tr>
        </thead>
      <% end %>

      <!--thead>
        
      <tr>
          <th><input type="checkbox"></th>
          <th>Name</th>
          <th>Email</th>
          <th>Last Login</th>
          <th>Last Login IP</th>
          <th>Status</th>
      </tr>
      </thead>
      <tbody>
      <tr>
          <td><input type="checkbox"></td>
          <td><a href="/edit-administrator.html">Himanshu Mistry</a></td>
          <td>daniel@php2india.com</td>
          <td>12th Sept 2012 12:00 PM</td>
          <td>192.178.121.112</td>
          <td>Active</td>
         
      </tr>
      <tr>
          <td><input type="checkbox"></td>
          <td><a href="/edit-administrator.html">Jignesh Nakrani</a></td>
          <td>jignesh.nakrani@php2india.com</td>
          <td>12th Sept 2012 12:00 PM</td>
          <td>192.178.121.112</td>
          <td>Active</td>
         
      </tr>
      </tbody-->
      </table>
      <%else%>
      <table class="table table-bordered table-striped">
        <thead>
        <tr>
          <th><input type="checkbox" onclick="checkAll(document.cfrm);" name="check_all" id="check_all"></th>
          <th>Name</th>
          <th>Email</th>
          <th>Last Login</th>
          <th>Last Login IP</th>
          <th>Status</th>
        </tr>
        </thead>
      </table>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>No Admin Found</strong>
      </div>      
      <%end%>
  </div>
  </form>
  </div>
</div><!--/.fluid-container-->


<!--h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%# @posts.each do |post| %>
  <tr>
    <td><%#= post.name %></td>
    <td><%#= post.title %></td>
    <td><%#= post.content %></td>
    <td><%#= link_to 'Show', post %></td>
    <td><%#= link_to 'Edit', edit_post_path(post) %></td>
    <td><%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<%# end %>
</table>

<br />

<%#= link_to 'New Post', new_post_path %>
-->

app/views/admins/login_log.html.erb
<div class="container-fluid">
    <div class="row-fluid">
    <div class="span10">
        <div class="page-header">
        <h2>Login Logs</h2>
        </div>
        <ul class="breadcrumb">
        <li><a href="#">Home</a> <span class="divider">/</span></li>
        <li class="active">Login Logs</li>
        </ul>
        <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">?</button>
        <strong>Oh snap!</strong> Change a few things up and try submitting again.
        </div>
        <form class="form-search">
        <input type="text" class="input-large search-query">
        <button type="submit" class="btn btn-primary">Search</button>
        <div class="pull-right">
        <button type="submit" class="btn btn-inverse">Delete</button>
        </div>
        </form>
    
        <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th><input type="checkbox"></th>
            <th>Name</th>
            <th>Email</th>
            <th>Login Time</th>
            <th>Logout Time</th>
            <th>IP</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td><input type="checkbox"></td>
            <td><a href="/edit-administrator.html">Himanshu Mistry</a></td>
            <td>daniel@php2india.com</td>
            <td>12th Sept 2012 12:00 PM</td>
            <td>12th Sept 2012 12:00 PM</td>
            <td>192.189.1.112</td>
           
        </tr>
        <tr>
           <td><input type="checkbox"></td>
            <td><a href="/edit-administrator.html">Himanshu Mistry</a></td>
            <td>daniel@php2india.com</td>
            <td>12th Sept 2012 12:00 PM</td>
            <td>12th Sept 2012 12:00 PM</td>
            <td>192.189.1.112</td>
           
        </tr>
        </tbody>
        </table>
    </div>
    </div>
</div><!--/.fluid-container-->

app/views/admins/new.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="page-header">
      <h2>New Administrator</h2>
    </div>
    <%= render 'form' %>
  </div>
</div>

<%#= link_to 'Back', posts_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/admins/sign_in.html.erb
<style>
  
        body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }
</style>

<div class="container">
<% if flash[:msg]%>
<div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <strong></strong><%=flash[:msg]%>
</div>
<%end%>
<div id="msg"></div>
  <form class="form-signin" action="/sign_in_act" method="post" name="sfrm" id="sfrm">
    <h2 class="form-signin-heading">Please sign in</h2>
    Email<input type="text" class="input-block-level" placeholder="Email address" id="email" name="email">
    Password<input type="password" class="input-block-level" placeholder="Password" id="pswd" name="pswd">
    <label class="checkbox">
      <input type="checkbox" value="remember-me"> Remember me
    </label>
    <button class="btn btn-large btn-primary" type="button" onclick="return frmsub(document.sfrm);">Sign in</button>
  </form>

</div>
<script>
  function frmsub(frm){
    if ($("#email").val() == "") {
      $("#msg").html('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert">x</button><strong>Please Your enter Email</strong></div>');
      return false;
    }
    if ($("#pswd").val() == "") {
      $("#msg").html('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert">x</button><strong>Please Your enter Password</strong></div>');
      return false;
    }
    
    frm.submit();
    return true;
  }
</script>

app/views/partial/_header.html.erb
<div class="navbar">
<div class="navbar-inner">
    <%= link_to image_tag('logo.png',:width=>"200"),"/dashboard",:class=>"brand" %>
    <ul class="nav">
           <li><%= link_to "Home","/dashboard" %></li>
        <li class="divider-vertical"></li>
        <!--li><%#= link_to "Administrators","/admins" %></li-->
        <li class="dropdown">
            <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Master <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                <li><a tabindex="-1" href="/admins">Administrator</a></li>
                <li><a tabindex="-1" href="/position">Positions</a></li>
                <li><a tabindex="-1" href="/country">Country</a></li>
                <li><a tabindex="-1" href="/state">State</a></li>
                <li><a tabindex="-1" href="/city">Cities</a></li>
            </ul>
        </li>
        <li class="divider-vertical"></li>
        <li><%= link_to "Login Logs","/loginlogs" %></li>
        <li class="divider-vertical"></li>
        <li><%= link_to "Customers","/customers" %></li>
        <li class="divider-vertical"></li>
        <!--li><%#= link_to "Meter Readings","/electricities" %></li-->
        <li class="dropdown">
            <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Electric Readings <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                <li><a tabindex="-1" href="#">Gas Readings</a></li>
                <li><a tabindex="-1" href="#">LPG Readings</a></li>
                <li><a tabindex="-1" href="#">Water Readings</a></li>
            </ul>
        </li>

        <li class="divider-vertical"></li>
        <!--li><%#= link_to "Settings","/setting" %></li-->
        <li class="dropdown">
            <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Settings<b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                <li><a tabindex="-1" href="#">General Settings</a></li>
                <li><a tabindex="-1" href="#"> Email Templates</a></li>
            </ul>
        </li>
        <%if !session[:login_id].nil?%>
            <li><%= link_to "Sign Out","/signout" %></li>
        <%end%>
    </ul>
</div>
</div>
<script>
    $('.dropdown-toggle').dropdown();
</script>