config/routes.rb
EmmPhase2::Application.routes.draw do
 
  resources :admins
  resources :customers
  resources :loginlogs
  resources :electricities
  resource :dashboards
  resource :settings
  resource :countries
  resource :states
  resource :cities
  resource :positions
  match "/state_change" => "admins#state_change"
  match "/city_change" => "admins#city_change"
  match "/" => "admins#sign_in"
  match "/customer/action" => "customers#action"
  match "sign_in" => "admins#sign_in"
  match "sign_in_act" => "admins#sign_in_act"
  match "/admin" => "admins#index"
  match "/signout" => "admins#sign_out"
  match "/signin" => "admins#sign_in"
  match "/loginlog/action" => "loginlogs#action"
  match "/admin/action" => "admins#action"
  match "/dashboard" => "dashboards#index"
  match "/setting" => "settings#index"
  match "/customer" => "customers#index"
  match "/loginlog" => "loginlogs#index"
  match "/electricity" => "electricities#index"
  match "/meterreading" => "electricities#import_csv"
  match "/test" => "electricities#test"
  match "/insert_to_customer_panel" => "electricities#insert_to_customer_panel"
  match "/cron_test" => "electricities#cron_test"
  
  
  match "/country" => "countries#index"
  match "/country/action" => "countries#action"
  match "/state" => "states#index"
  match "/state/action" => "states#action"
  match "/city" => "cities#index"
  match "/city/action" => "cities#action"
  match "/position" => "positions#index"
  match "/position/action" => "positions#action"
  
 
  
  

   root :to => 'admins#sign_in'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/state.rb
class State < ActiveRecord::Base
   attr_accessible :country_id, :name, :code, :description, :status
   validates_presence_of :country_id, :name, :code, :description, :status
   belongs_to :country
   has_many :cities
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
    respond_to :json, :html
  def index
    if params[:state] == "1"
        @state = 0
        sort = "ASC"
    else
        @state = 1
        sort = "DESC"
    end
    case  params[:sorton]
        when    "1"
            field = 'first_name'
        when    "2"
            field = 'email'
        when    "3"
            field = 'status'
    else
        field = 'created_at'
    end
    if params[:keyword]!='' && params[:keyword]!=nil && params[:option]!='' && params[:option]!=nil
        if params[:alpha_search] == 'Yes'
        
            keyword = [" #{params[:option] .strip()} LIKE ?", "%#{params['keyword'].strip()}%"]
        else
            keyword = [" #{params[:option] .strip()} LIKE ?", "%#{params['keyword'].strip()}%"]
        end
    else
        keyword = []
    end
    order_by = "#{field} #{sort}"
    
    @states = State.paginate(:page => params[:page], :per_page => 10,:conditions => keyword, :order => order_by)
  end

  def new
    @state = State.new
   # render :text=> @state.inspect and return false

  end

  def edit
    @state = State.find(params[:id])
   # render :text=> @state.country.inspect and return false
  end

  def create
    @state = State.new(params[:state])
  
    respond_to do |format|
      if @state.save
        flash[:msg] = 'State was successfully created.'
        format.html { redirect_to :controller => 'states', :action => 'index' }
      else
        format.html { render action: "new" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @state = State.find(params[:id])
    respond_to do |format|
      if @state.update_attributes(params[:state])
        flash[:msg] = 'State was successfully Updated.'
        format.html { redirect_to :controller => 'states', :action => 'index'}
      else
        format.html { render action: "edit" }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  def action
   #   render :text=> params.inspect and return false
    @ids = params[:chk]
    clength = @ids.length
    if params[:action_val] == "active"
      State.update_all(["status = ? ", '0'],["id IN (?)", @ids])
      flash[:msg] = "#{clength} Record(s) Active sucessfully."
    end
    if params[:action_val] == "inactive"
      State.update_all(["status = ? ", '1'],["id IN (?)", @ids] )
      flash[:msg] = "#{clength} Record(s) InActive sucessfully."
    end
    if params[:action_val] == "delete"
     @states =  State.find(:all, :conditions => ["id in (?)", @ids])
     @states.each do |country|
       country.destroy
     end
     flash[:msg] = "#{clength} Record(s) Delete sucessfully."
    end
    redirect_to :controller => 'states', :action => 'index'
    #format.html { redirect_to :controller => 'customers', :action => 'index' }
  end

end

app/views/states/!!!show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/states/_edit_form.html.erb
<div class="container-fluid">
    <div class="row-fluid">
    <div class="span10">
         <!--div class="page-header">
        <h2>Add Customer</h2>
        </div-->
        <ul class="breadcrumb">
        <li><a href="#">Master</a> <span class="divider">/</span></li>
          <%if @state.id.nil?%>
            <li class="active">Add State</li>
          <%else%>
            <li class="active">Edit State</li>
          <%end%>
        </ul>
        <!--div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">?</button>
        <strong>Oh snap!</strong> Change a few things up and try submitting again.
        </div-->
        <%=form_for @state,:url => {:action => "update",:id => @state[:id]},:html => {:multipart => true ,:class => "form-horizontal"} do |f|%>
        
        <% if @state.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <strong><%=@state.errors.full_messages[0] %></strong>
          </div>
        <% end %>
        <div class="span5 well">
          <!--form class="form-horizontal"-->
        <h4>State</h4>
          <div class="control-group">
            <%= f.label :country_id,:class=>"control-label"%>
              <div class="controls">
               <%= select_tag("state[country_id]", options_from_collection_for_select(Country.all, "id", "name", params[:state_id].to_i),:selected => @state.country.id) %>
              </div>
          </div>        
          <div class="control-group">
            <%= f.label :name ,:class=>"control-label"%>
              <div class="controls">
                <%= f.text_field :name,:class=>"span8",:placeholder=>"State Name"%>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :code,:class=>"control-label"%>
              <div class="controls">
                <%= f.text_field :code,:class=>"span8",:placeholder=>"State Code"%>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :description,:class=>"control-label"%>
              <div class="controls">
                <%= f.text_area :description,:rows=>"3",:placeholder=>"Description"%>
              </div>
          </div>

          <div class="control-group">
            <%= f.label :status,:class=>"control-label"%>
              <div class="controls">
                <%= f.select :status, [['Active','0'],['Inactive','1']],{:selected =>@state.status },{:class => 'span8'} %>
                <br><br>
                   <%= f.submit 'Submit',:class=>'btn'%>
              </div>
          </div>
        <!--/form-->
        </div>

        <!--/form-->
        </div>
        
        <!--/form-->
        </div>        
      <%end%>
    </div>
    </div>	
</div><!--/.fluid-container-->





<!--
<%#= form_for(@post) do |f| %>
  <%# if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <%# @post.errors.full_messages.each do |msg| %>
        <li><%#= msg %></li>
      <%# end %>
      </ul>
    </div>
  <%# end %>

  <div class="field">
    <%#= f.label :name %><br />
    <%#= f.text_field :name %>
  </div>
  <div class="field">
    <%#= f.label :title %><br />
    <%#= f.text_field :title %>
  </div>
  <div class="field">
    <%#= f.label :content %><br />
    <%#= f.text_area :content %>
  </div>
  <div class="actions">
    <%#= f.submit %>
  </div>
<%# end %>
-->

app/views/states/_form.html.erb
<div class="container-fluid">
    <div class="row-fluid">
    <div class="span10">
         <!--div class="page-header">
        <h2>Add Customer</h2>
        </div-->
        <ul class="breadcrumb">
        <li><a href="#">Master</a> <span class="divider">/</span></li>
          <%if @state.id.nil?%>
            <li class="active">Add State</li>
          <%else%>
            <li class="active">Edit State</li>
          <%end%>
        </ul>
        <!--div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">?</button>
        <strong>Oh snap!</strong> Change a few things up and try submitting again.
        </div-->
        
        <%= form_for(@state,:html=>{:class=>"form-horizontal"}) do |f| %>
        <% if @state.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <strong><%=@state.errors.full_messages[0] %></strong>
          </div>
        <% end %>
        <div class="span5 well">
          <!--form class="form-horizontal"-->
        <h4>State</h4>
          <div class="control-group">
            <%= f.label :country_id,:class=>"control-label"%>
              <div class="controls">
               <%= select_tag("state[country_id]", options_from_collection_for_select(Country.all, "id", "name", params[:state_id].to_i)) %>

                <%#= select(:country, :id, (Country.all.collect{|country| [country.name]}).uniq) %>
                <%#= f.select :country_id, [['Active','0'],['Inactive','1']],{},{:class => 'span8'} %>
              </div>
          </div>        
          <div class="control-group">
            <%= f.label :name ,:class=>"control-label"%>
              <div class="controls">
                <%= f.text_field :name,:class=>"span8",:placeholder=>"State Name"%>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :code,:class=>"control-label"%>
              <div class="controls">
                <%= f.text_field :code,:class=>"span8",:placeholder=>"State Code"%>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :description,:class=>"control-label"%>
              <div class="controls">
                <%= f.text_area :description,:rows=>"3",:placeholder=>"Description"%>
              </div>
          </div>

          <div class="control-group">
            <%= f.label :status,:class=>"control-label"%>
              <div class="controls">
                <%= f.select :status, [['Active','0'],['Inactive','1']],{},{:class => 'span8'} %>
                <br><br>
                   <%= f.submit 'Submit',:class=>'btn'%>
              </div>
          </div>
        <!--/form-->
        </div>

        <!--/form-->
        </div>
        
        <!--/form-->
        </div>        
      <%end%>
    </div>
    </div>	
</div><!--/.fluid-container-->





<!--
<%#= form_for(@post) do |f| %>
  <%# if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <%# @post.errors.full_messages.each do |msg| %>
        <li><%#= msg %></li>
      <%# end %>
      </ul>
    </div>
  <%# end %>

  <div class="field">
    <%#= f.label :name %><br />
    <%#= f.text_field :name %>
  </div>
  <div class="field">
    <%#= f.label :title %><br />
    <%#= f.text_field :title %>
  </div>
  <div class="field">
    <%#= f.label :content %><br />
    <%#= f.text_area :content %>
  </div>
  <div class="actions">
    <%#= f.submit %>
  </div>
<%# end %>
-->

app/views/states/edit.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="page-header">
      <h2>Edit Customer</h2>
    </div>

    <%= render 'edit_form' %>
  </div>
</div>

<%#= link_to 'Show', @post %> |
<%#= link_to 'Back', posts_path %>

app/views/states/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
  <div class="span10">
      <div class="page-header">
      <h2>State</h2>
      </div>
      <ul class="breadcrumb">
      <li><a href="#">Master</a> <span class="divider">/</span></li>
      <li class="active">State</li>
      </ul>
      <% if flash[:msg]%>
        <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert">x</button>
              <strong>Well done!</strong><%=flash[:msg]%>
        </div>
      <%end%>
      <!--div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">?</button>
      <strong>Oh snap!</strong> Change a few things up and try submitting again.
      </div-->
      <div class="left_topform">
      <%= form_tag("/state", :method => "PUT",:name=>"cfrm" ,:id=>"cfrm") do %>
        <%=text_field_tag 'keyword',params[:keyword],:class => 'input-large search-query'%>
        <%=select_tag 'option', options_for_select([["Select Field",""],["Name","name"], ["Code","code"],["Status","status"]], params[:option])%>

      <button type="submit" class="btn btn-primary">Search</button>
      <%end%>
      </div>
      <%= form_tag("/state/action", :method => "PUT",:name=>"cfrm" ,:id=>"cfrm") do %>
      <input type="hidden" name="action_val" id ="action_val" value="">
      <div class="pull-right">
      <button type="submit" class="btn btn-inverse" onclick="return Action(document.cfrm,'active');">Make Active</button>
      <button type="submit" class="btn btn-inverse" onclick="return Action(document.cfrm,'inactive');">Make Inactive</button>
      <button type="submit" class="btn btn-inverse" onclick="return Action(document.cfrm,'delete');">Delete</button>
      <%= link_to 'New state', new_states_path ,:class=>"btn btn-inverse"%>
      </div>
      <div class="clearfix"></div>
      <!--div ><b> Total Number Of Records : </b><%=@states.count%></div-->
   <%if @states.length > 0%>
      <table class="table table-bordered table-striped">
        <thead>
			<tr>
			    <th><input type="checkbox" onclick="checkAll(document.cfrm);" name="check_all" id="check_all"></th>
			    <th>Name </th>
				<th>Country Name</th>
			    <th>Code</th>
			    <th>Description</th>
			    <th>Status</th>
			    <th>Create At</th>
			</tr>
        </thead>
       
        <% @states.each do |state| %>
          <thead>
          <tr>
          <td><input type="checkbox" id="iId" value="<%=state.id%>" name="chk[]" ></td>
          <td><%= link_to state.name ,"states/edit/#{state.id}"%></td>
          <td><%=state.country.name%></td>
          <td><%=state.code%></td>
          
          <td><%= state.description %></td>
          <td><%if state.status == 0%>Active<%else%>Inactive<%end%></td>
          <td><%= state.created_at.strftime("%d %B %Y  %M:%H") %></td>
        </tr>
        </thead>
      <% end %>

      <!--thead>
        
      <tr>
          <th><input type="checkbox"></th>
          <th>Name</th>
          <th>Email</th>
          <th>Last Login</th>
          <th>Last Login IP</th>
          <th>Status</th>
      </tr>
      </thead>
      <tbody>
      <tr>
          <td><input type="checkbox"></td>
          <td><a href="/edit-stateistrator.html">Himanshu Mistry</a></td>
          <td>daniel@php2india.com</td>
          <td>12th Sept 2012 12:00 PM</td>
          <td>192.178.121.112</td>
          <td>Active</td>
         
      </tr>
      <tr>
          <td><input type="checkbox"></td>
          <td><a href="/edit-stateistrator.html">Jignesh Nakrani</a></td>
          <td>jignesh.nakrani@php2india.com</td>
          <td>12th Sept 2012 12:00 PM</td>
          <td>192.178.121.112</td>
          <td>Active</td>
         
      </tr>
      </tbody-->
      </table>
      <%else%>
      <table class="table table-bordered table-striped">
        <thead>
			<tr>
			    <th><input type="checkbox" onclick="checkAll(document.cfrm);" name="check_all" id="check_all"></th>
			    <th>Name </th>
			    <th>Code</th>
			    <th>Description</th>
			    <th>Status</th>
			    <th>Create At</th>
			</tr>
        </thead>
      </table>
            <div class="alert alert-warning">
              <button type="button" class="close" data-dismiss="alert">x</button>
              <strong>No state Found</strong>
            </div> 
      <%end%>
      <%= page_entries_info %>
      <%= will_paginate @states , :renderer => BootstrapPagination::Rails%>
  </div>
  <%end%>
  </div>
</div><!--/.fluid-container-->

<!--h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%# @posts.each do |post| %>
  <tr>
    <td><%#= post.name %></td>
    <td><%#= post.title %></td>
    <td><%#= post.content %></td>
    <td><%#= link_to 'Show', post %></td>
    <td><%#= link_to 'Edit', edit_post_path(post) %></td>
    <td><%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<%# end %>
</table>

<br />

<%#= link_to 'New Post', new_post_path %>
-->

app/views/states/new.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="page-header">
      <h2>New State</h2>
    </div>

    <%= render 'form' %>
  </div>
</div>


<%#= link_to 'Back', posts_path %>