config/routes.rb
EmmPhase2::Application.routes.draw do
 
  resources :admins
  resources :customers
  resources :loginlogs
  resources :electricities
  resource :dashboards
  resource :settings
  resource :countries
  resource :states
  resource :cities
  resource :positions
  match "/state_change" => "admins#state_change"
  match "/city_change" => "admins#city_change"
  match "/" => "admins#sign_in"
  match "/customer/action" => "customers#action"
  match "sign_in" => "admins#sign_in"
  match "sign_in_act" => "admins#sign_in_act"
  match "/admin" => "admins#index"
  match "/signout" => "admins#sign_out"
  match "/signin" => "admins#sign_in"
  match "/loginlog/action" => "loginlogs#action"
  match "/admin/action" => "admins#action"
  match "/dashboard" => "dashboards#index"
  match "/setting" => "settings#index"
  match "/customer" => "customers#index"
  match "/loginlog" => "loginlogs#index"
  match "/electricity" => "electricities#index"
  match "/meterreading" => "electricities#import_csv"
  match "/test" => "electricities#test"
  match "/insert_to_customer_panel" => "electricities#insert_to_customer_panel"
  match "/cron_test" => "electricities#cron_test"
  
  
  match "/country" => "countries#index"
  match "/country/action" => "countries#action"
  match "/state" => "states#index"
  match "/state/action" => "states#action"
  match "/city" => "cities#index"
  match "/city/action" => "cities#action"
  match "/position" => "positions#index"
  match "/position/action" => "positions#action"
  
 
  
  

   root :to => 'admins#sign_in'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :customer_id,:name,:email,:licence_id,:status,:city,:country,:postalcode,:phone,:phone_code,:heroku_url,:heroku_username,:heroku_password,:git_url,:amazon_url,:db_host,:db_name,:db_username,:db_password,:db_port
  belongs_to :csvinfo
  validates_presence_of :customer_id,:name,:email,:licence_id,:status,:city,:country,:postalcode,:phone,:phone_code,:heroku_url,:heroku_username,:git_url,:amazon_url,:db_host,:db_name,:db_username,:db_password,:db_port
  validates_presence_of :heroku_password,:on => :create
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => " Invalid Format"
  validates :email,:uniqueness => true,:on => :create
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    respond_to :json, :html
    # GET /posts
  # GET /posts.json
  def index
   # render :text => "hi" and return false
    #@customers = Customer.all
  if params[:state] == "1"
      @state = 0
      sort = "ASC"
  else
      @state = 1
      sort = "DESC"
  end
  case  params[:sorton]
      when    "1"
          field = 'first_name'
      when    "2"
          field = 'email'
      when    "3"
          field = 'status'
  else
      field = 'created_at'
  end
  if params[:keyword]!='' && params[:keyword]!=nil && params[:option]!='' && params[:option]!=nil
      if params[:alpha_search] == 'Yes'
      
          keyword = [" #{params[:option] .strip()} LIKE ?", "%#{params['keyword'].strip()}%"]
    #  elsif params[:option] == 'status'
# @value = (params["keyword"].downcase =="inactive" || params["keyword"].downcase =="active")? ((params["keyword"].downcase == "inactive")? 1 : 0) : -1
      #    keyword = [" #{params[:option] .strip()} =?",@value]	
      else
          keyword = [" #{params[:option] .strip()} LIKE ?", "%#{params['keyword'].strip()}%"]
      end
  else
      keyword = []
  end
  order_by = "#{field} #{sort}"
    
    @customers = Customer.paginate(:page => params[:page], :per_page => 10,:conditions => keyword, :order => order_by)

 #   respond_to do |format|
 #     format.html # index.html.erb
 #     format.json { render json: @customers }
  #  end
  end

  # GET /posts/1
  # GET /posts/1.json


  # GET /posts/new
  # GET /posts/new.json
  def new
    @customer = Customer.new

 #   respond_to do |format|
  #    format.html # new.html.erb
 #     format.json { render json: @customer }
  #  end
  end

  # GET /posts/1/edit
  def edit
    @customer = Customer.find(params[:id])
    @csvinfos = Csvinfo.paginate(:page => params[:page], :per_page => 10,:conditions => ['customer_id =?', @customer.id])
   
    #@csvinfos = Csvinfo.find(:all,:conditions =>['customer_id =?', @customer.id])
    #render :text => @csvinfos.inspect and return false
  end

  # POST /posts
  # POST /posts.json
  def create
    #render :text => params.inspect and return false
    params[:customer][:country] = params[:country]
    params[:customer][:status] = params[:status]
    @customer = Customer.new(params[:customer])
  
   # render :text => @customer.inspect and return false
    respond_to do |format|
      if @customer.save
        flash[:msg] = 'Customer was successfully created.'
        format.html { redirect_to :controller => 'customers', :action => 'index' }
        #format.json { render json: @customer, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @customer = Customer.find(params[:id])
    @csvinfos = Csvinfo.paginate(:page => params[:page], :per_page => 10,:conditions => ['customer_id =?', @customer.id])
# render :text => @csvinfos.inspect and return false
    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        flash[:msg] = 'Customer was successfully Updated.'
        format.html { redirect_to :controller => 'customers', :action => 'index'}
        #format.html { redirect_to (:action => :index), notice: 'Customer was successfully updated.' }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  def action
    @ids = params[:chk]
    clength = @ids.length
   # render :text => params.inspect and return false
    if params[:action_val] == "active"
     # render :text => params.inspect and return false
      Customer.update_all(["status = ? ", 'active'],["id IN (?)", @ids])
      flash[:msg] = "#{clength} Record(s) Active sucessfully."
    end
    if params[:action_val] == "inactive"
      #render :text => 'inactive' and return false
      Customer.update_all(["status = ? ", 'inactive'],["id IN (?)", @ids] )
      flash[:msg] = "#{clength} Record(s) InActive sucessfully."
    end
    if params[:action_val] == "delete"
     @cusomers =  Customer.find(:all, :conditions => ["id in (?)", @ids])
     @customers.each do |cusotmer|
       cusotmer.destroy
     end
     flash[:msg] = "#{clength} Record(s) Delete sucessfully."
    end
    redirect_to :controller => 'customers', :action => 'index'
    #format.html { redirect_to :controller => 'customers', :action => 'index' }
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_edit_form.html.erb
<div class="container-fluid">
    <div class="row-fluid">
    <div class="span10">
         <!--div class="page-header">
        <h2>Add Customer</h2>
        </div-->
        <ul class="breadcrumb">
        <li><a href="#">Home</a> <span class="divider">/</span></li>
        <li class="active">Edit Customer</li>
        </ul>
        <!--div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">?</button>
        <strong>Oh snap!</strong> Change a few things up and try submitting again.
        </div-->
        <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#profile" data-toggle="tab">Profile</a></li>
            <li><a href="#data" data-toggle="tab">CSV Data</a></li>
        </ul>
        <%= form_for(@customer,:html=>{:class=>"form-horizontal"}) do |f| %>
        <% if @customer.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <strong><%=@customer.errors.full_messages[0] %></strong>
          </div>
        <% end %>
        <div class="tab-content">
            <div class="tab-pane active" id="profile">
        <div class="span5 well">
          <!--form class="form-horizontal"-->
        <h4>General Information</h4>
        <div class="control-group">
          <label class="control-label" for="inputEmail">Customer ID</label>
          <div class="controls">
            <%= f.text_field :customer_id,:class=>"span8",:placeholder=>"Customer ID"%>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="inputEmail">Licence ID</label>
          <div class="controls">
            <%= f.text_field :licence_id,:class=>"span8",:placeholder=>"Licence ID"%>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :name ,:class=>"control-label"%>
          <div class="controls">
            <%= f.text_field :name,:class=>"span8",:placeholder=>"Name"%>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :email,:class=>"control-label"%>
            <div class="controls">
              <%= f.text_field :email,:class=>"span8",:placeholder=>"Email"%>
            </div>
        </div>
        <div class="control-group">
          <%= f.label :city,:class=>"control-label"%>
            <div class="controls">
              <%= f.text_field :city,:class=>"span8",:placeholder=>"City"%>
            </div>
        </div>
        <div class="control-group">
          <%= f.label :country ,:class=>"control-label"%>
            <div class="controls">
              <%= select_tag(:country, options_for_select(['US','Canada'],{ :selected => @customer.country } ),{:class=>"span8"}) %>
            <!--select class="span8" name="country">
                <option value="US">US</option>
                <option value="Canada">Canada</option>
              </select-->
            </div>
        </div>
        <div class="control-group">
          <%= f.label :postalcode,:class=>"control-label"%>
          <div class="controls">
            <%= f.text_field :postalcode,:class=>"span8",:placeholder=>"Postal Code"%>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :phone ,:class=>"control-label"%>
          <div class="controls">
              <%= f.text_field :phone_code,:class=>"input-mini",:placeholder=>"Phone"%>
              <%= f.text_field :phone,:class=>"span8",:placeholder=>"Phone"%>
            </div>
        </div>
        
        <div class="control-group">
            <%= f.label :status ,:class=>"control-label"%>
            <div class="controls">
              <%= select_tag(:status, options_for_select(['Active','Inactive'],{ :selected => @customer.status } ),{:class=>"span4"}) %>
            <!--select class="span4" name="customer[status]">
                <option>Active</option>
                <option>Inactive</option>
              </select--><br><br>
                 <button type="submit" class="btn">Submit</button>
            </div>
        
        </div>
        
        
        
        <!--/form-->
        </div>
        <div class="span5 well">
            <form class="form-horizontal">
        <h4>Server Information</h4>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Heroku</label>
            <div class="controls">
              <%= f.text_field :heroku_url,:class=>"span8",:placeholder=>"Application URL"%>
            </div>
            </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Username</label>
            <div class="controls">
              <%= f.text_field :heroku_username,:class=>"span8",:placeholder=>"Username"%>
            </div>
            </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Password</label>
            <div class="controls">
              <%= f.password_field :heroku_password,:class=>"span8",:placeholder=>"Password"%>
            </div>
            </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">GitURL</label>
            <div class="controls">
              <%= f.text_field :git_url,:class=>"span8",:placeholder=>"Git URL"%>
            </div>
            </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">CSV Storage</label>
            <div class="controls">
              <%= f.text_field :amazon_url,:class=>"span8",:placeholder=>"Amzon S3 URL"%>
            </div>
            </div>
        <!--/form-->
        </div>
        
        <div class="span5 well">
            <form class="form-horizontal">
        <h4>DB Information</h4>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Host</label>
            <div class="controls">
              <%= f.text_field :db_host,:class=>"span8",:placeholder=>"Database Host Name"%>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Database</label>
            <div class="controls">
              <%= f.text_field :db_name,:class=>"span8",:placeholder=>"Database Name"%>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">User</label>
            <div class="controls">
              <%= f.text_field :db_username,:class=>"span8",:placeholder=>"Database User Name"%>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Port</label>
            <div class="controls">
              <%= f.text_field :db_port,:class=>"span8",:placeholder=>"Database Port Name"%>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Password</label>
            <div class="controls">
              <%= f.text_field :db_password,:class=>"span8",:placeholder=>"Database Password Name"%>
            </div>
        </div>
        <!--/form-->
        </div>
        
        
      <%end%>
                </div>
            	<div class="tab-pane" id="data">
                <%if @csvinfos.length > 0%>
				<table class="table table-bordered table-striped">
				<thead>
				    <tr>
					<th><input type="checkbox"></th>
					<th>CSV</th>
					<th>Date</th>
					<th>Verified</th>
					<th>Loaded</th>
					<th>Total Data</th>
					<th>View</th>
					<th>Status</th>
				    </tr>
				</thead>
				<tbody>
                        <% @csvinfos.each do |csvinfo| %>

				    <tr>
                        <td><input type="checkbox" id="iId" value="<%=csvinfo.id%>" name="chk[]" ></td>
                        <td><%=csvinfo.name%></td>
                        <td><%=csvinfo.upload_date.strftime("%dth %b %Y  %H:%M %p")%></td>
                        <td><%=csvinfo.verified%></td>
                        <td><%=csvinfo.loaded%></td>
                        <td><%=csvinfo.totaldata%></td>
                        <td><%= link_to "view" ,edit_electricity_path(csvinfo.id)%></td>
                        <td><%=csvinfo.status%></td>
				    </tr>
                        <%end%>
				</tbody>
				</table>
                <%else%>
                    <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                        <th><input type="checkbox"></th>
                        <th>CSV</th>
                        <th>Date</th>
                        <th>Verified</th>
                        <th>Loaded</th>
                        <th>Total Data</th>
                        <th>View</th>
                        <th>Status</th>
                        </tr>
                    </thead>

                    </table>
                    <strong>No Csv Found</strong>
                <%end%>
                <%#= will_paginate @csvinfos , :renderer => BootstrapPagination::Rails%>
			      </div>
			</div>

            </div>
    </div>	
</div><!--/.fluid-container-->





<!--
<%#= form_for(@post) do |f| %>
  <%# if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <%# @post.errors.full_messages.each do |msg| %>
        <li><%#= msg %></li>
      <%# end %>
      </ul>
    </div>
  <%# end %>

  <div class="field">
    <%#= f.label :name %><br />
    <%#= f.text_field :name %>
  </div>
  <div class="field">
    <%#= f.label :title %><br />
    <%#= f.text_field :title %>
  </div>
  <div class="field">
    <%#= f.label :content %><br />
    <%#= f.text_area :content %>
  </div>
  <div class="actions">
    <%#= f.submit %>
  </div>
<%# end %>
-->

app/views/customers/_form.html.erb
<div class="container-fluid">
    <div class="row-fluid">
    <div class="span10">
         <!--div class="page-header">
        <h2>Add Customer</h2>
        </div-->
        <ul class="breadcrumb">
        <li><a href="#">Home</a> <span class="divider">/</span></li>
        <li class="active">Add Customer</li>
        </ul>
        <!--div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">?</button>
        <strong>Oh snap!</strong> Change a few things up and try submitting again.
        </div-->
        
        <%= form_for(@customer,:html=>{:class=>"form-horizontal"}) do |f| %>
        <% if @customer.errors.any? %>
          <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <strong><%=@customer.errors.full_messages[0] %></strong>
          </div>
        <% end %>
        <div class="span5 well">
          <!--form class="form-horizontal"-->
        <h4>General Information</h4>
        <div class="control-group">
          <label class="control-label" for="inputEmail">Customer ID</label>
          <div class="controls">
            <%= f.text_field :customer_id,:class=>"span8",:placeholder=>"Customer ID"%>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="inputEmail">Licence ID</label>
          <div class="controls">
            <%= f.text_field :licence_id,:class=>"span8",:placeholder=>"Licence ID"%>
          </div>
        </div>

        <div class="control-group">
          <%= f.label :name ,:class=>"control-label"%>
          <div class="controls">
            <%= f.text_field :name,:class=>"span8",:placeholder=>"Name"%>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :email,:class=>"control-label"%>
            <div class="controls">
              <%= f.text_field :email,:class=>"span8",:placeholder=>"Email"%>
            </div>
        </div>
        <div class="control-group">
          <%= f.label :city,:class=>"control-label"%>
            <div class="controls">
              <%= f.text_field :city,:class=>"span8",:placeholder=>"City"%>
            </div>
        </div>
        <div class="control-group">
          <%= f.label :country ,:class=>"control-label"%>
            <div class="controls">
              <%= select_tag(:country, options_for_select(['US','Canada'],{ :selected => @customer.country } ),{:class=>"span8"}) %>
            <!--select class="span8" name="country">
                <option value="US">US</option>
                <option value="Canada">Canada</option>
              </select-->
            </div>
        </div>
        <div class="control-group">
          <%= f.label :postalcode,:class=>"control-label"%>
          <div class="controls">
            <%= f.text_field :postalcode,:class=>"span8",:placeholder=>"Postal Code"%>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :phone ,:class=>"control-label"%>
          <div class="controls">
              <%= f.text_field :phone_code,:class=>"input-mini",:placeholder=>"Phone"%>
              <%= f.text_field :phone,:class=>"span8",:placeholder=>"Phone"%>
            </div>
        </div>
        
        <div class="control-group">
            <%= f.label :status ,:class=>"control-label"%>
            <div class="controls">
              <%= select_tag(:status, options_for_select(['Active','Inactive'],{ :selected => @customer.status } ),{:class=>"span4"}) %>
            <!--select class="span4" name="customer[status]">
                <option>Active</option>
                <option>Inactive</option>
              </select--><br><br>
                 <button type="submit" class="btn">Submit</button>
            </div>
        
        </div>
        
        
        
        <!--/form-->
        </div>
        <div class="span5 well">
            <form class="form-horizontal">
        <h4>Server Information</h4>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Heroku</label>
            <div class="controls">
              <%= f.text_field :heroku_url,:class=>"span8",:placeholder=>"Application URL"%>
            </div>
            </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Username</label>
            <div class="controls">
              <%= f.text_field :heroku_username,:class=>"span8",:placeholder=>"Username"%>
            </div>
            </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Password</label>
            <div class="controls">
              <%= f.password_field :heroku_password,:class=>"span8",:placeholder=>"Password"%>
            </div>
            </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">GitURL</label>
            <div class="controls">
              <%= f.text_field :git_url,:class=>"span8",:placeholder=>"Git URL"%>
            </div>
            </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">CSV Storage</label>
            <div class="controls">
              <%= f.text_field :amazon_url,:class=>"span8",:placeholder=>"Amzon S3 URL"%>
            </div>
            </div>
        <!--/form-->
        </div>
        
        <div class="span5 well">
            <form class="form-horizontal">
        <h4>DB Information</h4>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Host</label>
            <div class="controls">
              <%= f.text_field :db_host,:class=>"span8",:placeholder=>"Database Host Name"%>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Database</label>
            <div class="controls">
              <%= f.text_field :db_name,:class=>"span8",:placeholder=>"Database Name"%>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">User</label>
            <div class="controls">
              <%= f.text_field :db_username,:class=>"span8",:placeholder=>"Database User Name"%>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Port</label>
            <div class="controls">
              <%= f.text_field :db_port,:class=>"span8",:placeholder=>"Database Port Name"%>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputEmail">Password</label>
            <div class="controls">
              <%= f.text_field :db_password,:class=>"span8",:placeholder=>"Database Password Name"%>
            </div>
        </div>
        <!--/form-->
        </div>        
      <%end%>
    </div>
    </div>	
</div><!--/.fluid-container-->





<!--
<%#= form_for(@post) do |f| %>
  <%# if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%#= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <%# @post.errors.full_messages.each do |msg| %>
        <li><%#= msg %></li>
      <%# end %>
      </ul>
    </div>
  <%# end %>

  <div class="field">
    <%#= f.label :name %><br />
    <%#= f.text_field :name %>
  </div>
  <div class="field">
    <%#= f.label :title %><br />
    <%#= f.text_field :title %>
  </div>
  <div class="field">
    <%#= f.label :content %><br />
    <%#= f.text_area :content %>
  </div>
  <div class="actions">
    <%#= f.submit %>
  </div>
<%# end %>
-->

app/views/customers/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
  <div class="span10">
      <div class="page-header">
      <h2>Customers</h2>
      </div>
      <ul class="breadcrumb">
      <li><a href="#">Home</a> <span class="divider">/</span></li>
      <li class="active">Customers</li>
      </ul>
      <% if flash[:msg]%>
        <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert">x</button>
              <strong>Well done!</strong><%=flash[:msg]%>
        </div>
      <%end%>
      <!--div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">?</button>
      <strong>Oh snap!</strong> Change a few things up and try submitting again.
      </div-->
      <div class="left_topform">
      <form class="form-search" action="/customer" name="sfrm" id="sfrm" method="put">
        <%=text_field_tag 'keyword',params[:keyword],:class => 'input-large search-query'%>
        <%=select_tag 'option', options_for_select([["Select Field",""],["Name","name"], ["Email","email"],["Status","status"]], params[:option])%>

      <button type="submit" class="btn btn-primary">Search</button>
      </form>
      </div>
      <form class="form-search" action="/customer/action" name="cfrm" id="cfrm" method="put">
      <input type="hidden" name="action_val" id ="action_val" value="">
      <div class="pull-right">
      <button type="submit" class="btn btn-inverse" onclick="return Action(document.cfrm,'active');">Make Active</button>
      <button type="submit" class="btn btn-inverse" onclick="return Action(document.cfrm,'inactive');">Make Inactive</button>
      <button type="submit" class="btn btn-inverse" onclick="return Action(document.cfrm,'delete');">Delete</button>
      <%= link_to 'New Customer', new_customer_path ,:class=>"btn btn-inverse"%>
      </div>
      <div class="clearfix"></div>
      <!--div ><b> Total Number Of Records : </b><%=@customers.count%></div-->
   <%if @customers.length > 0%>
      <table class="table table-bordered table-striped">
        <thead>
			<tr>
			    <th><input type="checkbox" onclick="checkAll(document.cfrm);" name="check_all" id="check_all"></th>
			    <th>Customer ID </th>
			    <th>Name</th>
			    <th>Email</th>
			    <th>Licence ID</th>
			    <th>Status</th>
			</tr>
        </thead>
       
        <% @customers.each do |customer| %>
          <thead>
          <tr>
          <td><input type="checkbox" id="iId" value="<%=customer.id%>" name="chk[]" ></td>
          <td><%= link_to customer.customer_id ,edit_customer_path(customer)%></td>
          
          <td><%=customer.name%></td>
          
          <td><%= customer.email %></td>
          <td><%= customer.licence_id %></td>
          <td><%= customer.status.capitalize %></td>
        </tr>
        </thead>
      <% end %>

      <!--thead>
        
      <tr>
          <th><input type="checkbox"></th>
          <th>Name</th>
          <th>Email</th>
          <th>Last Login</th>
          <th>Last Login IP</th>
          <th>Status</th>
      </tr>
      </thead>
      <tbody>
      <tr>
          <td><input type="checkbox"></td>
          <td><a href="/edit-customeristrator.html">Himanshu Mistry</a></td>
          <td>daniel@php2india.com</td>
          <td>12th Sept 2012 12:00 PM</td>
          <td>192.178.121.112</td>
          <td>Active</td>
         
      </tr>
      <tr>
          <td><input type="checkbox"></td>
          <td><a href="/edit-customeristrator.html">Jignesh Nakrani</a></td>
          <td>jignesh.nakrani@php2india.com</td>
          <td>12th Sept 2012 12:00 PM</td>
          <td>192.178.121.112</td>
          <td>Active</td>
         
      </tr>
      </tbody-->
      </table>
      <%else%>
      <table class="table table-bordered table-striped">
        <thead>
			<tr>
			    <th><input type="checkbox" onclick="checkAll(document.cfrm);" name="check_all" id="check_all"></th>
			    <th>Customer ID </th>
			    <th>Name</th>
			    <th>Email</th>
			    <th>Licence ID</th>
			    <th>Status</th>
			</tr>
        </thead>
      </table>
            <div class="alert alert-warning">
              <button type="button" class="close" data-dismiss="alert">x</button>
              <strong>No Customer Found</strong>
            </div> 
      <%end%>
      <%= page_entries_info %>
      <%= will_paginate @customers , :renderer => BootstrapPagination::Rails%>
  </div>
  </form>
  </div>
</div><!--/.fluid-container-->

<!--h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%# @posts.each do |post| %>
  <tr>
    <td><%#= post.name %></td>
    <td><%#= post.title %></td>
    <td><%#= post.content %></td>
    <td><%#= link_to 'Show', post %></td>
    <td><%#= link_to 'Edit', edit_post_path(post) %></td>
    <td><%#= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<%# end %>
</table>

<br />

<%#= link_to 'New Post', new_post_path %>
-->

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>